### ISSUE TITLE
`execa is not a function` when picking device

### ISSUE THREAD

**Issue by yunusefendi52** [Clancey/vscode-comet#36]
It seems there is a problem when importing execa, I tried modify extension.js to import execa properly
before:
`const execa = __webpack_require__(/*! execa */ "./node_modules/execa/index.js");`
to:
`const execa = __webpack_require__(/*! execa */ "./node_modules/execa/index.js").execa;`

added .execa at the end for workaround

I use v0.7.0 and on mac

**Comment by Ghostbird** [comment]
Have the same issue. It occurs to me that in the package.json both `@types/execa` and `execa` are listed. When I NPM install that, it warns that `@types/execa` is a stub that should not be used. Could it be that something went wrong because of that?

A direct import of `execa` does not return a callable function.

**Comment by jessejiang0214** [comment]
Fixed in this PR https://github.com/Clancey/vscode-comet/pull/37

**Comment by Redth** [comment]
Give this build a try: https://github.com/Clancey/vscode-comet/actions/runs/3519810694#artifacts

Not entirely sure what was going on there but this is working locally now for me.

**Comment by yunusefendi52** [comment]
tried using latest commit, it's fixed now. thanks!
